http:
  middlewares:
    chain-cloudflare:
      chain:
        middlewares:
          - redirect-web-to-websecure@internal
          - cloudflare-ipwhitelist
          - secureHeaders
    cloudflare-ipwhitelist:
      ipWhiteList:
        sourceRange:
          - "192.168.0.0/24"
          - "192.168.2.0/24"
          - "173.245.48.0/20"
          - "103.21.244.0/22"
          - "103.22.200.0/22"
          - "103.31.4.0/22"
          - "141.101.64.0/18"
          - "108.162.192.0/18"
          - "190.93.240.0/20"
          - "188.114.96.0/20"
          - "197.234.240.0/22"
          - "198.41.128.0/17"
          - "162.158.0.0/15"
          - "104.16.0.0/12"
          - "172.64.0.0/13"
          - "131.0.72.0/22"
          - "2400:cb00::/32"
          - "2606:4700::/32"
          - "2803:f800::/32"
          - "2405:b500::/32"
          - "2405:8100::/32"
          - "2a06:98c0::/29"
          - "2c0f:f248::/32"
    secureHeaders:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - X-Forwarded-Host
          - Cf-Connecting-Ip"
        stsSeconds: 63072000
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: same-origin
        #featurePolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
  routers:
    router-dsm:
      entryPoints:
        - websecure
      rule: "Host(`maison.alexetnico.com`) || Host(`maison.napadelice.ch`)"
      service: service-dsm
      #middlewares:
      #  - chain-cloudflare
      tls:
        certResolver: cloudflare
    router-hass:
      entryPoints:
        - websecure
      rule: "Host(`hass.alexetnico.com`) || Host(`hass.napadelice.ch`)"
      service: service-hass
      tls:
        certResolver: cloudflare
    router-nodered:
      entryPoints:
        - websecure
      rule: Host(`nodered.alexetnico.com`)
      service: service-nodered
      tls:
        certResolver: cloudflare
    router-guacamole:
      entryPoints:
        - websecure
      rule: Host(`guacamole.alexetnico.com`)
      service: service-guacamole
      tls:
        certResolver: cloudflare     
    router-emby:
      entryPoints:
        - websecure
      rule: "Host(`emby.alexetnico.com`) || Host(`emby.napadelice.ch`)"
      service: service-emby
      tls:
        certResolver: cloudflare
    router-homebridge:
      entryPoints:
        - websecure
      rule: Host(`homebridge.alexetnico.com`)
      service: service-homebridge
      tls:
        certResolver: cloudflare
  services:    
    service-dsm:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "http://192.168.2.20:9200"
    service-hass:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "http://192.168.2.20:8123"
    service-nodered:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "http://192.168.2.20:1880"
    service-guacamole:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "http://192.168.2.20:8086"
    service-emby:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "http://192.168.2.20:8096"
    service-homebridge:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "http://192.168.2.20:8581"  
tcp:
  middlewares:
    cloudflare-ipwhitelist:
      ipWhiteList:
        sourceRange:
          - "192.168.0.0/24"
          - "192.168.2.0/24"
          - "173.245.48.0/20"
          - "103.21.244.0/22"
          - "103.22.200.0/22"
          - "103.31.4.0/22"
          - "141.101.64.0/18"
          - "108.162.192.0/18"
          - "190.93.240.0/20"
          - "188.114.96.0/20"
          - "197.234.240.0/22"
          - "198.41.128.0/17"
          - "162.158.0.0/15"
          - "104.16.0.0/12"
          - "172.64.0.0/13"
          - "131.0.72.0/22"
          - "2400:cb00::/32"
          - "2606:4700::/32"
          - "2803:f800::/32"
          - "2405:b500::/32"
          - "2405:8100::/32"
          - "2a06:98c0::/29"
          - "2c0f:f248::/32"  
  routers: 
    router-synoBackup:
      entryPoints:
        - synoBackup
      rule: "HostSNI(`*`)"
      service: service-synoBackup
      middlewares:
        - cloudflare-ipwhitelist  
    router-synoActiveBackup:
      entryPoints:
        - synoActiveBackup
      rule: "HostSNI(`*`)"
      service: service-synoActiveBackup
      middlewares:
        - cloudflare-ipwhitelist 
    router-synoDrive:
      rule: "HostSNI(`*`)"
      entrypoints:
        - synoDrive
      service: service-synoDrive

  services:
    service-synoBackup:
      loadBalancer:
        servers:
        - address: "192.168.2.20:6281"  
    service-synoDrive:
      loadBalancer:
        servers:
        - address: "192.168.2.20:6690"
    service-synoActiveBackup:
      loadBalancer:
        servers:
        - address: "192.168.2.20:5510"