global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
    web:
        address: :80
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
    websecure:
        address: :443
        http:
            tls:
                certResolver: cloudflare
    traefik:
        address: :8080   
    synoDrive:
        address: :6690/TCP
    synoBackup:
        address: :6281/TCP  
    synoActiveBackup:
        address: :5510/TCP
    metrics:
        address: ":8082"

ping: {}

log:
    level: debug
    filePath: /etc/traefik-log/traefik.log 

api:
  dashboard: true
  insecure: true
  debug: true

accessLog:
    filePath: /etc/traefik-log/access.log
    bufferingSize: 100
    fields: 
        headers:
            names:
                X-Forwarded-For: keep

providers:
    docker:
        endpoint: tcp://socket-proxy:2375
        watch: true
        exposedByDefault: false
    file:
      filename: /etc/traefik/rules.yaml

certificatesResolvers:
    cloudflare:
        acme:
            email: cloudflare@bordetnico.com
            storage: /etc/traefik/acme.json
            dnsChallenge:
                provider: cloudflare
                delayBeforeCheck: 0
                resolvers:
                - 1.1.1.1:53
                - 1.0.0.1:53

serversTransport:
    insecureSkipVerify: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true