substitutions:
  name: athom-smart-plug-v2-89b8e6
  friendly_name: Smart Plug V2 89b8e6
packages:
  Athom_Technology.Smart_Plug_V2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: RBsGbAI56i888T5BQXwb5RuEDt8pcOGkW7+ZlQaneps=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
